<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialGroupRepository extends EntityRepository
{
    public function getLeaves ()
    {
        $query = $this->_em->createQuery('SELECT mg FROM AppBundle:MaterialGroup mg WHERE mg.rightSide = mg.leftSide + 1');

        return $query->getResult();

    }
}
